/* The country list: ISO 3166-1 alpha-2 id (which is also the flag-icons
 * filename), display name, difficulty tier and alternative names accepted by
 * the guess box. Tiers: 1 = most people could name it, 2 = a flag enthusiast
 * would, 3 = deep cuts.
 */
export const COUNTRIES = [
  { id: "af", name: "Afghanistan", tier: 2 },
  { id: "al", name: "Albania", tier: 2 },
  { id: "dz", name: "Algeria", tier: 1 },
  { id: "ad", name: "Andorra", tier: 3 },
  { id: "ao", name: "Angola", tier: 2 },
  { id: "ag", name: "Antigua and Barbuda", tier: 3 },
  { id: "ar", name: "Argentina", tier: 1 },
  { id: "am", name: "Armenia", tier: 2 },
  { id: "au", name: "Australia", tier: 1 },
  { id: "at", name: "Austria", tier: 1 },
  { id: "az", name: "Azerbaijan", tier: 2 },
  { id: "bs", name: "Bahamas", tier: 2 },
  { id: "bh", name: "Bahrain", tier: 2 },
  { id: "bd", name: "Bangladesh", tier: 1 },
  { id: "bb", name: "Barbados", tier: 2 },
  { id: "by", name: "Belarus", tier: 3 },
  { id: "be", name: "Belgium", tier: 1 },
  { id: "bz", name: "Belize", tier: 3 },
  { id: "bj", name: "Benin", tier: 2 },
  { id: "bt", name: "Bhutan", tier: 2 },
  { id: "bo", name: "Bolivia", tier: 2 },
  { id: "ba", name: "Bosnia and Herzegovina", tier: 2 },
  { id: "bw", name: "Botswana", tier: 2 },
  { id: "br", name: "Brazil", tier: 1 },
  { id: "bn", name: "Brunei", tier: 3 },
  { id: "bg", name: "Bulgaria", tier: 2 },
  { id: "bf", name: "Burkina Faso", tier: 2 },
  { id: "bi", name: "Burundi", tier: 3 },
  { id: "cv", name: "Cabo Verde", tier: 3, alt: ["Cape Verde"] },
  { id: "kh", name: "Cambodia", tier: 2 },
  { id: "cm", name: "Cameroon", tier: 2 },
  { id: "ca", name: "Canada", tier: 1 },
  { id: "cf", name: "Central African Republic", tier: 3 },
  { id: "td", name: "Chad", tier: 2 },
  { id: "cl", name: "Chile", tier: 1 },
  { id: "cn", name: "China", tier: 1 },
  { id: "co", name: "Colombia", tier: 1 },
  { id: "km", name: "Comoros", tier: 3 },
  { id: "cg", name: "Congo", tier: 3, alt: ["Republic of the Congo","Congo-Brazzaville"] },
  { id: "cr", name: "Costa Rica", tier: 2 },
  { id: "ci", name: "Cote d'Ivoire", tier: 2, alt: ["Ivory Coast"] },
  { id: "hr", name: "Croatia", tier: 1 },
  { id: "cu", name: "Cuba", tier: 1 },
  { id: "cy", name: "Cyprus", tier: 2 },
  { id: "cz", name: "Czechia", tier: 1, alt: ["Czech Republic"] },
  { id: "cd", name: "DR Congo", tier: 2, alt: ["Democratic Republic of the Congo","Zaire"] },
  { id: "dk", name: "Denmark", tier: 1 },
  { id: "dj", name: "Djibouti", tier: 3 },
  { id: "dm", name: "Dominica", tier: 3 },
  { id: "do", name: "Dominican Republic", tier: 2 },
  { id: "ec", name: "Ecuador", tier: 2 },
  { id: "eg", name: "Egypt", tier: 1 },
  { id: "sv", name: "El Salvador", tier: 3 },
  { id: "gq", name: "Equatorial Guinea", tier: 3 },
  { id: "er", name: "Eritrea", tier: 3 },
  { id: "ee", name: "Estonia", tier: 2 },
  { id: "sz", name: "Eswatini", tier: 3, alt: ["Swaziland"] },
  { id: "et", name: "Ethiopia", tier: 2 },
  { id: "fj", name: "Fiji", tier: 3 },
  { id: "fi", name: "Finland", tier: 1 },
  { id: "fr", name: "France", tier: 1 },
  { id: "ga", name: "Gabon", tier: 3 },
  { id: "gm", name: "Gambia", tier: 3 },
  { id: "ge", name: "Georgia", tier: 2 },
  { id: "de", name: "Germany", tier: 1 },
  { id: "gh", name: "Ghana", tier: 1 },
  { id: "gr", name: "Greece", tier: 1 },
  { id: "gd", name: "Grenada", tier: 3 },
  { id: "gt", name: "Guatemala", tier: 2 },
  { id: "gn", name: "Guinea", tier: 2 },
  { id: "gw", name: "Guinea-Bissau", tier: 3 },
  { id: "gy", name: "Guyana", tier: 3 },
  { id: "ht", name: "Haiti", tier: 3 },
  { id: "hn", name: "Honduras", tier: 2 },
  { id: "hu", name: "Hungary", tier: 1 },
  { id: "is", name: "Iceland", tier: 1 },
  { id: "in", name: "India", tier: 1 },
  { id: "id", name: "Indonesia", tier: 1 },
  { id: "ir", name: "Iran", tier: 1 },
  { id: "iq", name: "Iraq", tier: 2 },
  { id: "ie", name: "Ireland", tier: 1 },
  { id: "il", name: "Israel", tier: 1 },
  { id: "it", name: "Italy", tier: 1 },
  { id: "jm", name: "Jamaica", tier: 1 },
  { id: "jp", name: "Japan", tier: 1, alt: ["Nippon"] },
  { id: "jo", name: "Jordan", tier: 2 },
  { id: "kz", name: "Kazakhstan", tier: 2 },
  { id: "ke", name: "Kenya", tier: 1 },
  { id: "ki", name: "Kiribati", tier: 3 },
  { id: "xk", name: "Kosovo", tier: 3 },
  { id: "kw", name: "Kuwait", tier: 2 },
  { id: "kg", name: "Kyrgyzstan", tier: 3 },
  { id: "la", name: "Laos", tier: 2 },
  { id: "lv", name: "Latvia", tier: 2 },
  { id: "lb", name: "Lebanon", tier: 1 },
  { id: "ls", name: "Lesotho", tier: 3 },
  { id: "lr", name: "Liberia", tier: 3 },
  { id: "ly", name: "Libya", tier: 2 },
  { id: "li", name: "Liechtenstein", tier: 3 },
  { id: "lt", name: "Lithuania", tier: 2 },
  { id: "lu", name: "Luxembourg", tier: 2 },
  { id: "mg", name: "Madagascar", tier: 2 },
  { id: "mw", name: "Malawi", tier: 3 },
  { id: "my", name: "Malaysia", tier: 2 },
  { id: "mv", name: "Maldives", tier: 3 },
  { id: "ml", name: "Mali", tier: 2 },
  { id: "mt", name: "Malta", tier: 2 },
  { id: "mh", name: "Marshall Islands", tier: 3 },
  { id: "mr", name: "Mauritania", tier: 3 },
  { id: "mu", name: "Mauritius", tier: 3 },
  { id: "mx", name: "Mexico", tier: 1 },
  { id: "fm", name: "Micronesia", tier: 3 },
  { id: "md", name: "Moldova", tier: 3 },
  { id: "mc", name: "Monaco", tier: 2 },
  { id: "mn", name: "Mongolia", tier: 2 },
  { id: "me", name: "Montenegro", tier: 3 },
  { id: "ma", name: "Morocco", tier: 1 },
  { id: "mz", name: "Mozambique", tier: 3 },
  { id: "mm", name: "Myanmar", tier: 2, alt: ["Burma"] },
  { id: "na", name: "Namibia", tier: 3 },
  { id: "nr", name: "Nauru", tier: 3 },
  { id: "np", name: "Nepal", tier: 2 },
  { id: "nl", name: "Netherlands", tier: 1, alt: ["Holland"] },
  { id: "nz", name: "New Zealand", tier: 1 },
  { id: "ni", name: "Nicaragua", tier: 3 },
  { id: "ne", name: "Niger", tier: 2 },
  { id: "ng", name: "Nigeria", tier: 1 },
  { id: "kp", name: "North Korea", tier: 2, alt: ["DPRK"] },
  { id: "mk", name: "North Macedonia", tier: 2, alt: ["Macedonia"] },
  { id: "no", name: "Norway", tier: 1 },
  { id: "om", name: "Oman", tier: 2 },
  { id: "pk", name: "Pakistan", tier: 1 },
  { id: "pw", name: "Palau", tier: 3 },
  { id: "ps", name: "Palestine", tier: 1 },
  { id: "pa", name: "Panama", tier: 2 },
  { id: "pg", name: "Papua New Guinea", tier: 2 },
  { id: "py", name: "Paraguay", tier: 3 },
  { id: "pe", name: "Peru", tier: 1 },
  { id: "ph", name: "Philippines", tier: 1 },
  { id: "pl", name: "Poland", tier: 1 },
  { id: "pt", name: "Portugal", tier: 1 },
  { id: "qa", name: "Qatar", tier: 2 },
  { id: "ro", name: "Romania", tier: 2 },
  { id: "ru", name: "Russia", tier: 1 },
  { id: "rw", name: "Rwanda", tier: 2 },
  { id: "kn", name: "Saint Kitts and Nevis", tier: 3 },
  { id: "lc", name: "Saint Lucia", tier: 3 },
  { id: "vc", name: "Saint Vincent and the Grenadines", tier: 3 },
  { id: "ws", name: "Samoa", tier: 3 },
  { id: "sm", name: "San Marino", tier: 3 },
  { id: "st", name: "Sao Tome and Principe", tier: 3 },
  { id: "sa", name: "Saudi Arabia", tier: 1 },
  { id: "sn", name: "Senegal", tier: 2 },
  { id: "rs", name: "Serbia", tier: 2 },
  { id: "sc", name: "Seychelles", tier: 3 },
  { id: "sl", name: "Sierra Leone", tier: 3 },
  { id: "sg", name: "Singapore", tier: 1 },
  { id: "sk", name: "Slovakia", tier: 2 },
  { id: "si", name: "Slovenia", tier: 2 },
  { id: "sb", name: "Solomon Islands", tier: 3 },
  { id: "so", name: "Somalia", tier: 2 },
  { id: "za", name: "South Africa", tier: 1 },
  { id: "kr", name: "South Korea", tier: 1 },
  { id: "ss", name: "South Sudan", tier: 3 },
  { id: "es", name: "Spain", tier: 1 },
  { id: "lk", name: "Sri Lanka", tier: 2 },
  { id: "sd", name: "Sudan", tier: 2 },
  { id: "sr", name: "Suriname", tier: 3 },
  { id: "se", name: "Sweden", tier: 1 },
  { id: "ch", name: "Switzerland", tier: 1 },
  { id: "sy", name: "Syria", tier: 2 },
  { id: "tw", name: "Taiwan", tier: 2 },
  { id: "tj", name: "Tajikistan", tier: 3 },
  { id: "tz", name: "Tanzania", tier: 2 },
  { id: "th", name: "Thailand", tier: 1 },
  { id: "tl", name: "Timor-Leste", tier: 3, alt: ["East Timor"] },
  { id: "tg", name: "Togo", tier: 3 },
  { id: "to", name: "Tonga", tier: 3 },
  { id: "tt", name: "Trinidad and Tobago", tier: 2 },
  { id: "tn", name: "Tunisia", tier: 2 },
  { id: "tr", name: "Turkey", tier: 1 },
  { id: "tm", name: "Turkmenistan", tier: 3 },
  { id: "tv", name: "Tuvalu", tier: 3 },
  { id: "ug", name: "Uganda", tier: 2 },
  { id: "ua", name: "Ukraine", tier: 1 },
  { id: "ae", name: "United Arab Emirates", tier: 1, alt: ["UAE"] },
  { id: "gb", name: "United Kingdom", tier: 1, alt: ["Great Britain","Britain","UK"] },
  { id: "us", name: "United States", tier: 1, alt: ["USA","America"] },
  { id: "uy", name: "Uruguay", tier: 2 },
  { id: "uz", name: "Uzbekistan", tier: 3 },
  { id: "vu", name: "Vanuatu", tier: 3 },
  { id: "va", name: "Vatican City", tier: 2, alt: ["Holy See"] },
  { id: "ve", name: "Venezuela", tier: 2 },
  { id: "vn", name: "Vietnam", tier: 1 },
  { id: "ye", name: "Yemen", tier: 2 },
  { id: "zm", name: "Zambia", tier: 2 },
  { id: "zw", name: "Zimbabwe", tier: 2 }
];
