/* Builds src/flag-art.js from the flag-icons SVG set (MIT).
 *
 *   npm install flag-icons svgo
 *   node tools/fetch-flags.mjs
 *
 * Each flag is optimised with SVGO, normalised to a 4:3 viewBox, and written
 * out as a minified SVG string. Vector rather than PNG so the board stays sharp
 * at any size on any phone, and so the whole thing still fits in one file.
 */
import { optimize } from 'svgo';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { COUNTRIES } from './countries.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Where the flag-icons package unpacked. Override with $FLAG_ICONS_DIR. */
const SRC = process.env.FLAG_ICONS_DIR ||
  join(root, 'node_modules/flag-icons/flags/4x3');

if (!existsSync(SRC)) {
  console.error(`No flag SVGs at ${SRC}. Run: npm install flag-icons`);
  process.exit(1);
}

const config = (precision) => ({
  multipass: true,
  plugins: [
    'preset-default',
    /* viewBox is what lets the art scale to any board size, so keep it and drop
     * the fixed width/height instead. */
    'removeDimensions',
    { name: 'convertPathData', params: { floatPrecision: precision } },
    { name: 'cleanupNumericValues', params: { floatPrecision: precision } }
  ]
});

/* A handful of flags are almost entirely one elaborate coat of arms (Serbia is
 * 177 KB on its own, Bolivia 100 KB) and between them they were half the total.
 * Those arms render a few dozen pixels tall, so coordinate precision below one
 * unit of a 640-wide viewBox is detail nobody can see. Dropping to integer
 * coordinates for the heavy ones only cuts them by around two thirds and leaves
 * every ordinary flag at full precision. */
const HEAVY_BYTES = 15000;

let out = [];
let before = 0, after = 0, missing = [];

for (const c of COUNTRIES) {
  const file = join(SRC, c.id + '.svg');
  if (!existsSync(file)) { missing.push(c.id); continue; }
  const raw = readFileSync(file, 'utf8');
  before += raw.length;

  let svg = optimize(raw, config(1)).data;
  if (svg.length > HEAVY_BYTES) svg = optimize(raw, config(0)).data;

  /* Everything must share one viewBox so the blank board is identical for every
   * flag -- a flag's real proportions would otherwise narrow the answer before
   * the first guess. 4x3 is what the source set uses. */
  if (!/viewBox=/.test(svg)) svg = svg.replace('<svg', '<svg viewBox="0 0 640 480"');

  /* Data URIs are simplest to embed and, being same-origin, do not taint a
   * canvas -- which matters because the game reads pixels back to compare. */
  after += svg.length;
  out.push({ id: c.id, name: c.name, tier: c.tier, alt: c.alt || [], svg });
}

if (missing.length) {
  console.error('missing flag art for:', missing.join(', '));
  process.exit(1);
}

const body = out.map((f) =>
  `{id:${JSON.stringify(f.id)},name:${JSON.stringify(f.name)},tier:${f.tier},` +
  `alt:${JSON.stringify(f.alt)},svg:${JSON.stringify(f.svg)}}`
).join(',\n');

writeFileSync(join(root, 'src/flag-art.js'),
  `/* GENERATED by tools/fetch-flags.mjs -- do not edit by hand.
 * Flag artwork from flag-icons (https://github.com/lipis/flag-icons), MIT licensed.
 * ${out.length} flags, SVGO-optimised.
 */
var FLAGS = [
${body}
];

FLAGS.sort(function (a, b) { return a.name < b.name ? -1 : 1; });
`);

console.log(`${out.length} flags`);
console.log(`svg: ${(before / 1024).toFixed(0)} KB -> ${(after / 1024).toFixed(0)} KB`);
